name: run-repo
run-name: "run `nilnesserr` for ${{github.event.inputs.repo_url}}"

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "the repo to run linter"
        default: "https://github.com/alingse/nilnesserr"
        required: true

permissions:
  issues: write

jobs:
  go-linter-runner-for-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run go-linter-runner use direct job config
        uses: alingse/go-linter-runner@main
        with:
          action: run
          go_version: "1.23.0"
          install_command: go install github.com/alingse/nilnesserr/cmd/nilnesserr@support-variadic-func
          linter_command: nilnesserr
          includes: "[\"call variadic function with a nil value error after check error\"]"
          excludes: "[]"
          issue_id: 15
          repo_url: ${{ inputs.repo_url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
